### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by RahulMR42**
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issues)

New samples # (demos / Illustrations )

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# How Has This Been Tested?

- [ ] Free Tier
- [ ] Always Free
- [ ] Paid 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Updated/Sorted AIO.md file
- [ ] My changes generate no new warnings.
- [ ] All the sensitive informations are masked or removed.
- [ ] All the links mentioned are valid and tested.
- [ ] Image names are seperated only with '-'.
- [ ] Added instruction to clone only this sample and links to other common sample pages.

### CODE REVIEW

**Comment by RahulMR42** [comment]
thanks in advance @ashok-cm

**Comment by jonschreiber** [comment]
Typo fix looks good to me 👍 

Are there any issues w/ licenses with that automated check?

**Comment by RahulMR42** [comment]
No issue for the license as we are using the same and we get this error for other devrel repos too .

**Comment by RahulMR42** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jonschreiber** [comment]
Confirmed with @RahulMR42  that license check is a warning, not that a package has an unsupported license

**Comment by jonschreiber** [comment]
oops sorry! hit the wrong button. Approved by me 👍

**Review by jonschreiber — APPROVED** [review]
typo fix looks good to me

**Comment by RahulMR42** [comment]
> oops sorry! hit the wrong button. Approved by me 👍

Thank you @jonschreiber

**Pull request merged**
